networks:
  caddy:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /app/
          ignore:
            - node_modules/
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - caddy

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgresdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - caddy

  # reverseproxy:
  #   image: caddy/caddy:latest
  #   container_name: caddy
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   depends_on:
  #     - web
  #   networks:
  #     - caddy

volumes:
  pgdata:
  # caddy_data:
  # caddy_config:
