version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /app/
          ignore:
            - node_modules/
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgresdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
